/**
 * Terms of Service Page
 * Legal terms and conditions for BaatCheet - Light Theme
 */

import { Link } from 'react-router-dom';
import { FileText, AlertCircle, Users, Shield, Scale, Ban, Mail, RefreshCw } from 'lucide-react';
import Header from '../components/Header';
import Footer from '../components/Footer';

export default function Terms() {
  const lastUpdated = 'January 15, 2026';

  const sections = [
    {
      icon: FileText,
      title: 'Acceptance of Terms',
      content: `By accessing or using BaatCheet ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.

These terms apply to all users of the Service, including users who are also contributors of content, information, and other materials or services.`,
    },
    {
      icon: Users,
      title: 'User Accounts',
      content: `**Account Creation:** You must provide accurate and complete information when creating an account.

**Account Security:** You are responsible for maintaining the security of your account credentials. Do not share your password with others.

**Age Requirement:** You must be at least 13 years old to use this Service. Users under 18 should have parental consent.

**Account Termination:** We reserve the right to terminate accounts that violate these terms.`,
    },
    {
      icon: Shield,
      title: 'Acceptable Use',
      content: `You agree to use the Service only for lawful purposes. You shall not:

• Generate or share illegal, harmful, or offensive content
• Attempt to manipulate or bypass AI safety measures
• Use the Service to harass, abuse, or harm others
• Infringe on intellectual property rights
• Attempt to gain unauthorized access to our systems
• Use automated systems to access the Service excessively
• Reverse engineer or attempt to extract source code`,
    },
    {
      icon: Scale,
      title: 'Intellectual Property',
      content: `**Our Content:** The Service, including its design, code, and branding, is owned by BaatCheet. You may not copy or redistribute our intellectual property.

**Your Content:** You retain ownership of content you create. By using the Service, you grant us a license to use, store, and process your content to provide the Service.

**AI-Generated Content:** Content generated by our AI is provided "as-is." You are responsible for how you use AI-generated content.`,
    },
    {
      icon: Ban,
      title: 'Prohibited Activities',
      content: `The following activities are strictly prohibited:

• Creating content that promotes violence, hate, or discrimination
• Generating explicit adult content or content involving minors
• Impersonating others or creating fake identities
• Spreading misinformation or harmful conspiracy theories
• Using the Service for spam, phishing, or fraud
• Attempting to circumvent usage limits or billing
• Violating any applicable laws or regulations`,
    },
    {
      icon: AlertCircle,
      title: 'Disclaimers',
      content: `**AI Limitations:** Our AI is not perfect. It may produce incorrect, biased, or inappropriate responses. Always verify important information.

**No Warranty:** The Service is provided "as is" without warranties of any kind.

**Availability:** We do not guarantee uninterrupted access to the Service. We may modify or discontinue features at any time.

**Third-Party Services:** We are not responsible for third-party services integrated with our platform.`,
    },
    {
      icon: RefreshCw,
      title: 'Changes to Terms',
      content: `We may update these Terms of Service from time to time. We will notify users of significant changes via email or in-app notification.

Continued use of the Service after changes constitutes acceptance of the new terms.

Your continued use of the Service following any changes indicates your acceptance of the new terms.`,
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-emerald-50/30">
      {/* Header */}
      <Header transparent={false} />

      {/* Hero */}
      <section className="pt-24 pb-12 relative">
        <div className="absolute inset-0">
          <div className="absolute inset-0 bg-gradient-to-br from-emerald-100/40 via-transparent to-purple-100/40" />
        </div>
        
        <div className="max-w-4xl mx-auto px-4 sm:px-6 text-center relative z-10">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-100 border border-emerald-200 rounded-full text-emerald-700 text-sm mb-6">
            <Scale size={16} />
            <span>Legal Document</span>
          </div>
          
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-slate-800 mb-4">
            Terms of Service
          </h1>
          <p className="text-lg text-slate-600 max-w-2xl mx-auto">
            Please read these terms carefully before using BaatCheet.
          </p>
          <p className="text-sm text-slate-500 mt-4">
            Last updated: {lastUpdated}
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-12 px-4 sm:px-6">
        <div className="max-w-4xl mx-auto space-y-8">
          {sections.map((section, index) => (
            <div
              key={index}
              className="bg-white border border-slate-200 rounded-2xl p-6 sm:p-8 shadow-sm"
            >
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-xl bg-emerald-100 flex items-center justify-center flex-shrink-0">
                  <section.icon className="text-emerald-600" size={24} />
                </div>
                <div className="flex-1 min-w-0">
                  <h2 className="text-xl font-semibold text-slate-800 mb-4">
                    {section.title}
                  </h2>
                  <div className="text-slate-600 leading-relaxed whitespace-pre-line">
                    {section.content.split('\n').map((line, i) => {
                      if (line.startsWith('**') && line.includes(':**')) {
                        const [bold, rest] = line.split(':**');
                        return (
                          <p key={i} className="mb-2">
                            <strong className="text-slate-700">{bold.replace('**', '')}:</strong>
                            {rest}
                          </p>
                        );
                      }
                      if (line.startsWith('•')) {
                        return (
                          <p key={i} className="ml-4 mb-1">
                            {line}
                          </p>
                        );
                      }
                      return line ? <p key={i} className="mb-2">{line}</p> : <br key={i} />;
                    })}
                  </div>
                </div>
              </div>
            </div>
          ))}

          {/* Contact section */}
          <div className="bg-gradient-to-r from-emerald-50 to-cyan-50 border border-emerald-200 rounded-2xl p-6 sm:p-8 text-center">
            <Mail className="mx-auto text-emerald-500 mb-4" size={32} />
            <h3 className="text-xl font-semibold text-slate-800 mb-2">
              Questions about our Terms?
            </h3>
            <p className="text-slate-600 mb-4">
              If you have any questions about these Terms of Service, please contact us.
            </p>
            <a
              href="mailto:sharry00010@gmail.com"
              className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-600 hover:to-teal-600 text-white rounded-xl transition-colors shadow-lg shadow-emerald-500/25"
            >
              <Mail size={18} />
              Contact Us
            </a>
          </div>

          {/* Navigation links */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-8">
            <Link
              to="/privacy"
              className="text-emerald-600 hover:text-emerald-700 transition-colors"
            >
              Read our Privacy Policy →
            </Link>
            <span className="hidden sm:inline text-slate-300">•</span>
            <Link
              to="/help"
              className="text-emerald-600 hover:text-emerald-700 transition-colors"
            >
              Help & Support →
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <Footer />
    </div>
  );
}
